# Generated by Django 5.1.3 on 2024-12-31 09:59

import django.db.models.deletion
import read_manga.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("processing", "Processing"), ("ready", "Ready")],
                        default="processing",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MangaPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(upload_to=read_manga.models.manga_directory_path),
                ),
                (
                    "manga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="read_manga.manga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=read_manga.models.manga_directory_path),
                ),
                ("recognized_text", models.TextField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=read_manga.models.manga_directory_path,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "manga_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panels",
                        to="read_manga.mangapage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
